import { existsSync, mkdirSync, copyFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const distDir = join(projectRoot, 'dist');
const sourceSitemap = join(distDir, 'sitemap-0.xml');
const targetDir = join(distDir, 'id');
const targetSitemap = join(targetDir, 'sitemap-id.xml');
const sitemapIndex = join(distDir, 'sitemap-index.xml');

if (!existsSync(sourceSitemap)) {
  throw new Error('Expected sitemap-0.xml was not generated by Astro.');
}

mkdirSync(targetDir, { recursive: true });
copyFileSync(sourceSitemap, targetSitemap);
rmSync(sourceSitemap, { force: true });
rmSync(sitemapIndex, { force: true });

console.log('Created /id/sitemap-id.xml for Google Search Console.');
